spring.application.name=avocarbon-ai-platform

# =========================
# SERVER
# =========================
server.port=8080

# =========================
# POSTGRESQL DATABASE
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/avocarbon
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always